core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', CreateProducts.as_view(), name='create'),
    path('list/', ListProducts.as_view(), name='list'),
    path('edit/<slug>/', EditProduct.as_view(), name='edit'),
    path('detail/<slug>/', ProductDetail.as_view(), name='detail'),
    path('create-checkout-session/<slug>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('success/', SuccessView.as_view(), name='success'),
    path('webhooks/stripe/', stripe_webhook, name='webhooks-stripe'),
    path("library/<username>/", UserLibraryList.as_view(), name="library"),
    # path('test/', TestView.as_view(), name='test'),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('marketplace/', include(('marketplace.urls', 'marketplace'))),
    path('users/', include(('accounts.urls', 'users'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/models.py
import os
from django.conf import settings
from django.db import models
from django.core.validators import FileExtensionValidator

User = settings.AUTH_USER_MODEL

def marketplace_directory_path(instance, filename):
    name = 'marketplace/products/{0}/{1}'.format(instance.name, filename)
    fullpath = os.path.join(settings.MEDIA_ROOT, name)

    if os.path.exists(fullpath):
        os.remove(fullpath)
    
    return name

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to=marketplace_directory_path)
    slug = models.SlugField(unique=True)

    content_url = models.URLField(blank=True, null=True)
    # content_file = models.FileField(blank=True, null=True, validators=[FileExtensionValidator(allow_extensions=['mp3'])])
    content_file = models.FileField(blank=True, null=True)

    active = models.BooleanField(default=False)

    price = models.PositiveIntegerField(default=100)

    def __str__(self):
        return self.name
    
    def price_display(self):
        return '{0:.2f}'.format(self.price/100)

class PurchasedProduct(models.Model):
    email = models.EmailField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date_purchase = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
        

templates/pages/forms/createProduct.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}
    
{% block content %}
    {% if user.is_staff %}
    <!-- <div x-data="{open:false}" class="px-4 mt-4">
        <button @click="open=true" class="inline-flex px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
            Add New
        </button> -->

        <div class="container mx-auto flex justify-center items-center p-4 pt-2">
            <div class="flex-wrap w-full md:max-w-xl text-center">
                <h1 class="block text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl">{{ title }}</h1>
                <p class="mt-4 font-light text-lg text-gray-500 tracking-wide">What would you like to sell today?</p>
                <p class="font-semibold text-lg text-gray-500 tracking-wide">Music, Games, Videos, Files, URLs.</p>
            </div>
        </div>

        <!--POST MODAL-->
        {% include 'pages/forms/form.html' %}
        <!-- END POST MODAL -->

        <!-- <div class="p-2 flex">
            <a href="#" class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-blue-500">
                <i class='bx bx-store'></i>
                <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Store</span>
            </a>
            {% comment %} <a href="{% url 'product-create' %}" class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-green-500">
                <i class='bx bxs-plus-circle'></i>
                <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Create a Product</span>
            </a> {% endcomment %}
            <a href="#" class="w-1/3 flex space-x-2 justify-center items-center hover:bg-gray-100 dark:hover:bg-dark-third text-xl sm:text-3xl py-2 rounded-lg cursor-pointer text-yellow-500">
                <i class='bx bx-library'></i>
                <span class="text-xs sm:text-sm font-semibold text-gray-500 dark:text-dark-txt">Library</span>
            </a>
        </div> -->
    {% endif %}
{% endblock content %}

templates/pages/forms/editForm.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}
    
{% block content %}
    {% if user.is_staff %}
        <div class="container mx-auto flex justify-center items-center p-4 pt-2">
            <div class="flex-wrap w-full md:max-w-xl text-center">
                <h1 class="block text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl">{{ title }}</h1>
                <p class="mt-4 font-light text-lg text-gray-500 tracking-wide">Edit your products?</p>
                <p class="font-semibold text-lg text-gray-500 tracking-wide">Music, Games, Videos, Files, URLs.</p>
            </div>
        </div>

        <!--POST MODAL-->
        {% include 'pages/forms/form.html' %}
        <!-- END POST MODAL -->
    </div>
    {% endif %}
{% endblock content %}

templates/pages/forms/errors.html
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <span class="text-sm text-red-500 mb-2">{{ error }}</span><br>
    {% endfor %}
{% endif %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <span class="text-sm text-red-500 mb-2">{{ error }}</span><br>
	    {% endfor %}
	{% endfor %}
{% endif %}

templates/pages/forms/form.html
<div class="flex justify-center">
    <div
        class="align-bottom bg-white rounded-lg px-4 pt-5 pb-4 overflow-hidden shadow-xl sm:my-8 sm:align-middle sm:max-w-xl sm:w-full sm:p-6">

        <div class="relative">
            <div class="absolute inset-0 flex items-center" aria-hidden="true">
                <div class="w-full border-t dark:border-dark-second border-gray-300"></div>
            </div>
            <div class="relative flex justify-center my-4">
                <span class="px-2 bg-white dark:bg-dark-second text-sm dark:text-dark-txt text-gray-500">
                    Product Thumbnail Image
                </span>
            </div>
        </div>


        <form class="form-horizontal dark:text-dark-txt" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="photo" class="mt-4 block text-sm font-medium dark:text-dark-txt text-gray-700">
                Thumbnail
            </label>
            
            <div>
                <div class="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
                  <div class="space-y-1 text-center">
                    <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                      <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>
                    <div class="text-sm text-gray-600">
                      <label for="id_thumbnail" class="relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500">
                        <span>Upload a file</span>
                        {{form.thumbnail}}
                      </label>
                    </div>
                    <div class="text-xs text-gray-500">
                        <p class="">PNG, JPG, GIF up to 10MB</p>
                    </div>
                  </div>
                </div>
                <span class="text-sm text-red-500">{{form.thumbnail.errors}}</span>
              </div>

            <!-- This example requires Tailwind CSS v2.0+ -->
            <div class="relative">
                <div class="absolute inset-0 flex items-center" aria-hidden="true">
                    <div class="w-full border-t dark:border-dark-second border-gray-300"></div>
                </div>
                <div class="relative flex justify-center my-4">
                    <span class="px-2 bg-white dark:bg-dark-second text-sm dark:text-dark-txt text-gray-500">
                        Product Details
                    </span>
                </div>
            </div>

            <label for="photo" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                Name
            </label>
            {{form.name}}
            <span class="text-sm text-red-500">{{form.name.errors}}</span>

            <label for="photo" class="mt-4 block text-sm font-medium dark:text-dark-txt text-gray-700">
                Description
            </label>
            {{form.description}}
            <span class="text-sm text-red-500">{{form.description.errors}}</span>

            <label for="photo" class="mt-4  block text-sm font-medium dark:text-dark-txt text-gray-700">
                Price
            </label>
            {{form.price}}
            <span class="text-sm text-red-500">{{form.price.errors}}</span>

            <label for="photo" class="mt-4 block text-sm font-medium dark:text-dark-txt text-gray-700">
                Slug
            </label>
            <div class="mt-1 flex rounded-md shadow-sm">
                <span
                    class="inline-flex items-center px-3 rounded-l-md border border-r-0 dark:border-dark-second dark:bg-dark-second border-gray-300 bg-gray-50 dark:text-dark-txt text-gray-500 sm:text-sm">
                    domain.com/
                </span>
                {{form.slug}}
            </div>
            <span class="text-sm text-red-500">{{form.slug.errors}}</span>

            <div class="relative">
                <div class="absolute inset-0 flex items-center" aria-hidden="true">
                    <div class="w-full border-t dark:border-dark-second border-gray-300"></div>
                </div>
                <div class="relative flex justify-center">
                    <span class="px-2 my-4 bg-white dark:bg-dark-second text-sm dark:text-dark-txt text-gray-500">
                        What are you selling?
                    </span>
                </div>
            </div>

            <label for="photo" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                URL (Optional: paid url products)
            </label>

            {{form.content_url}}
            <span class="text-sm text-red-500">{{form.content_url.errors}}</span>

            <label for="photo" class="mt-4 block text-sm font-medium dark:text-dark-txt text-gray-700">
                Upload Content
            </label>

            <div class="">
                <div class="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
                  <div class="space-y-1 text-center">
                    <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                      <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                    </svg>
                    <div class="text-sm text-gray-600">
                      <label for="id_content_file" class="relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500">
                        <span>Upload a file</span>
                        {{form.content_file}} 
                      </label>
                    </div>
                    <div class="text-xs text-gray-500">
                        <p class="">PNG, JPG, GIF up to 10MB</p>
                    </div>
                  </div>
                </div>
                <span class="text-sm text-red-500">{{form.content_file.errors}}</span>
            </div>

            <label for="photo" class="mt-4 block text-sm font-medium dark:text-dark-txt text-gray-700">
                Publish or Draft?
            </label>
            {{form.active}}
            <span class="text-sm text-red-500">{{form.active.errors}}</span>

            <div class="control-group">
                <div class="controls">
                    <button class="mt-4 inline-flex float-right items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
                        Submit
                    </button>
                </div>
            </div>


        </form>



    </div>
</div>